download_path = "Please, set your download folder"
audio_path = "Please, set your audio foldr"
movies_path = "Please, set your movies folder" 
serial_path = "Please , set your serial folder"
pdf_path = "Please, set your pdf folder"
app_path = "Please, set your app folder"
picture_path = "Please, set your picture folder"
